controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

auth_oauth_check:
  path: oauth/check/{service}

change_language:
    path: '/change-language/{locale}'
    controller: 'App\Controller\LanguageController::changeLanguage'
